logstash:
  image: logstash
  container_name: logstash 
  restart: always
  ports:
    - "5044:5044"
    - "4560:4560"
    - "8080:8080"
  volumes:
    - ./conf:/config-dir
    - ./patterns:/opt/logstash/patterns
  external_links:
    - elasticsearch:elasticsearch
  command: logstash -f /config-dir
