version: '2'
services:
  filebeat:
    image: olinicola/filebeat
    container_name: filebeat 
    restart: always
    network_mode: "bridge"
    extra_hosts:
      - "logstash:127.0.0.1"
    volumes:
      - ./conf/filebeat.yml:/etc/filebeat/filebeat.yml
      - /var/log:/var/host/log
      - ./registry:/etc/registry
